#!/bin/bash
###########################################################################
# 						YDELTA
# Programmed by: Tim Racinsky        Date: July, 1993
# Copyright (c) 1993 David Huron
#
# Modifications:
#   Date:      Programmer:       Description:
# June 7/94	Tim Racinsky	Modified to use getopts
#
#
#	This shell program receives input from the command line and after 
# checking it, passes it to the program ydelta.awk.
#
INTERPRETATION=""
REG_EXP=""
HELP=""
FILENAME=""
FLAG=""
STNDIN=""
USAGE1="USAGE: ydelta -h                   (Help Screen)"
USAGE2="       ydelta [-s reg_exp] -i interpretation [file ...]"

if [ -z "$AWK_VER" ]
then
   if [ -f "/usr/bin/awk" ]
   then
      AWK_VER="/usr/bin/awk"
   elif [ -f "/usr/bin/gawk" ]
   then
      AWK_VER="/usr/bin/gawk"
   elif [ -f "/bin/awk" ]
   then
      AWK_VER="/bin/awk"
   elif [ -f "/bin/gawk" ]
   then
      AWK_VER="/bin/gawk"
   elif [ -f "/usr/sbin/awk" ]
   then
      AWK_VER="/usr/sbin/awk"
   elif [ -f "/usr/sbin/gawk" ]
   then
      AWK_VER="/usr/sbin/gawk"
   elif [ -f "/sbin/awk" ]
   then
      AWK_VER="/sbin/awk"
   elif [ -f "/sbin/gawk" ]
   then
      AWK_VER="/sbin/gawk"
   fi
fi
# 
while getopts hi:s: arg
do
	case "$arg" in
	s) 	REG_EXP="${OPTARG}";;
	i) 	INTERPRETATION="${OPTARG}";;
	h) 	HELP="ON";;
     [?]) echo "" 1>&2
		echo "$USAGE1" 1>&2
		echo "$USAGE2" 1>&2
		exit;;
	esac
done
shift `expr $OPTIND - 1`
# If the help variable has been specified, print the help screen
if [ -n "$HELP" ]
then
	if [ -f ${HUMDRUM}/bin/helpscrn/ydelta.hlp ]
	then
		cat ${HUMDRUM}/bin/helpscrn/ydelta.hlp
	else
		echo "No help available on this command."
	fi
	exit
fi
if [ "X$INTERPRETATION" = X ]
then
	echo "ydelta: ERROR: Missing interpretation." 1>&2
	echo "" 1>&2
	echo "$USAGE1" 1>&2
	echo "$USAGE2" 1>&2
	exit
fi
# Process any remaining filenames
while [ "$#" -ne 0 ]
do
	# A '-' specifies standard input
	if [ x"$1" = x- ]
	then
		# Only one '-' is allowed
		if [ -z "$STNDIN" ]
		then
			FILENAME="$FILENAME $1"
			STNDIN="ON"
			shift
		else
			shift
		fi
	elif [ -f "$1" ]
	then
		FILENAME="$FILENAME $1"
		shift
	else
		echo "ydelta: ERROR: File not found: $1" 1>&2
		FLAG="ON"
		shift
	fi
done	
# If only invalid files specified, exit
if [ "X$FILENAME" = X -a -n "$FLAG" ]
then
	exit
fi	
# Invoke ydelta.awk with the specified options.
$AWK_VER -f ${HUMDRUM}/bin/ydelta.awk  "DUMMY" "${REG_EXP:-null}" "$INTERPRETATION" $FILENAME
