#!/bin/sh
###################################################################
#
# URRHYTHM
#
# Programmed by: David Huron        Date: ?
# Copyright (c) 1993 David Huron
#
# Modifications:
#   Date:      Programmer:       Description:
# June 17/94	Tim Racinsky	Modified to work with getopts (and other things)
#
#	This shell program receives input from the command line and after 
# checking it, passes it to the program urrhythm.awk.
#
# OPTIONS allowed from command line:
#
#	-h prints help screen
#
FILENAME=""
HELP=""
FLAG=""
STNDIN=""
USAGE1="USAGE: urrhythm -h                (Help Screen)"
USAGE2="       urrhythm [file ...]"

if [ -z $AWK_VER ]
then
   AWK_VER=`which awk`
   if [ -z $AWK_VER ]
   then
      AWK_VER=`which gawk`
   fi
   if [ -z $AWK_VER ]
   then
      exit 1
   fi
fi

if [ -z $HUMDRUM ]
then
   HUMDRUM=`echo $PATH | tr : '\n' | grep 'humdrum/bin$' | head -n 1 | sed 's/\/bin$//'`
fi

# 
while getopts h arg
do
	case "$arg" in
	h) 	HELP="ON";;
     [?]) echo "" 1>&2
		echo "$USAGE1" 1>&2
		echo "$USAGE2" 1>&2
		exit ;;
	esac
done
shift `expr $OPTIND - 1`
# 
OPTIONS=""
FILENAME=""
# If -h parameter specified, print the help screen
if [ -n "$HELP" ]
then
	if [ -f ${HUMDRUM}/bin/helpscrn/urrhythm.hlp ]
	then
		cat ${HUMDRUM}/bin/helpscrn/urrhythm.hlp
	else
		echo "No help available on this command."
	fi
	exit
fi
# Process any remaining filenames
while [ "$#" -ne 0 ]
do
	# A '-' specifies standard input
	if [ x"$1" = x- ]
	then
		# Only one '-' may be used
		if [ -z "$STNDIN" ]
		then
			FILENAME="$FILENAME $1"
			STNDIN="ON"
			shift
		else
			shift
		fi
	elif [ -f "$1" ]
	then
		FILENAME="$FILENAME $1"
		shift
	else
		echo "urrhythm: ERROR: File not found: $1" 1>&2
		FLAG="ON"
		shift
	fi
done	
if [ -z $FILENAME ]
then
   FILENAME="-"
fi 
# If only invalid files specified, exit
if [ "X$FILENAME" = X -a -n "$FLAG" ]
then
	exit
fi	
$AWK_VER -f ${HUMDRUM}/bin/urrhythm.awk "DUMMY" $FILENAME
